export const DARKMODE = "darkmode"
export const CHANGE_DARK_MODE = "change_dark_mode"
export const LIGHT = "light"
export const DARK = "dark"
export const RESULT_NATION = "result_nation"
export const GLOBAL_RESULT = "global_result"
export const UPDATE_RESULT = "update_result"
export const LOADING_STATE = "loading_state"
export const UPDATE_LOADING = "update_loading"

export const HOST = "https://restcountries.com/v3.1/"