export const DARKMODE = "darkmode"
export const CHANGE_DARK_MODE = "change_dark_mode"
export const LIGHT = "light"
export const DARK = "dark"
export const RESULT_NATION = "result_nation"
export const GLOBAL_RESULT = "global_result"
export const UPDATE_RESULT = "update_result"
export const LOADING_STATE = "loading_state"
export const UPDATE_LOADING = "update_loading"

export const HOST_COUNTRIES = "https://restcountries.com/v3.1/"
export const HOST_PIXABAY = "https://pixabay.com/api/"
export const APP_NAME = "NationIn4"
export const SLOGAN = "Explore our world"
export const GOOGLE_API = "AIzaSyBGCcrTDkzG-S5r21z8wjSlTPFdzhL5cZ4"
export const PIXABAY_API = "19771499-04521ac454824ece63222f9ac"